{
 "title": "My custom dashboard",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Weather Server uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container_label_com_docker_compose_service=\"weather_server\"}",
     "legendFormat": "{{z}}"
    }
   ]
  },
  {
   "title": "Weather Telegram Bot uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container_label_com_docker_compose_service=\"weather_tgbot\"}"
    }
   ]
  },
  {
   "title": "Weather Website uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container_label_com_docker_compose_service=\"weather_website\"}"
    }
   ]
  }
 ]
}